src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from pm.views import user, project, issue, issue_status, issue_tag, version, group, role, settings, \
    issue_category, base, account

urlpatterns = [
    url(r'^$', base.homepage.as_view(), name='homepage'),

    # authentication
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^my/password$', auth_views.password_change,
        {'template_name': 'password.html', 'post_change_redirect': '/my/password'}, name='password_change'),

    # account
    url(r'^my/account$', account.MyAccount.as_view(), name='my_account'),
    url(r'^my/avatar$', account.MyAvatar.as_view(), name='my_avatar'),

    # project
    url(r'^projects/$', project.List.as_view(), name='project_list'),
    url(r'^projects/(?P<pk>\d+)/$', project.Detail.as_view(), name='project_detail'),
    url(r'^projects/add/$', project.Create.as_view(), name='project_add'),
    url(r'^projects/(?P<pk>\d+)/delete/$', project.Delete.as_view(), name='project_delete'),
    url(r'^projects/(?P<pk>\d+)/close/$', project.Close.as_view(), name='project_close'),
    url(r'^projects/(?P<pk>\d+)/reopen/$', project.Reopen.as_view(), name='project_reopen'),
    url(r'^projects/(?P<pk>\d+)/gantt/$', project.Gantt.as_view(), name='project_gantt'),

    # project settings
    url(r'^projects/(?P<pk>\d+)/settings/$', project.Settings.as_view(), name='project_settings'),
    url(r'^projects/(?P<pk>\d+)/settings/info/$', project.Update.as_view(), name='project_update'),
    url(r'^projects/(?P<pk>\d+)/settings/versions/$', version.List.as_view(), name='version_list'),
    url(r'^projects/(?P<pk>\d+)/settings/members/$', project.ListMember.as_view(), name='member_list'),
    url(r'^projects/(?P<pk>\d+)/settings/issue_categories/$', issue_category.List.as_view(), name='issue_category_list'),

    # member
    url(r'^projects/(?P<pk>\d+)/members/delete$', project.DeleteMember.as_view(), name='member_delete'),
    url(r'^projects/(?P<pk>\d+)/members/add$', project.CreateMember.as_view(), name='member_add'),
    url(r'^projects/(?P<pk>\d+)/members/roles$', project.MemberRoles.as_view(), name='member_roles'),

    # issue category
    url(r'^projects/(?P<pk>\d+)/issue_categories/add/$', issue_category.Create.as_view(), name='issue_category_add'),
    url(r'^issue_categories/(?P<pk>\d+)/update/$', issue_category.Update.as_view(), name='issue_category_update'),
    url(r'^issue_categories/(?P<pk>\d+)/delete/$', issue_category.Delete.as_view(), name='issue_category_delete'),

    # issue tag
    url(r'^issue_tags/$', issue_tag.List.as_view(), name='issue_tag_list'),
    url(r'^issue_tags/add/$', issue_tag.Create.as_view(), name='issue_tag_add'),
    url(r'^issue_tags/(?P<pk>\d+)/update/$', issue_tag.Update.as_view(), name='issue_tag_update'),
    url(r'^issue_tags/(?P<pk>\d+)/delete/$', issue_tag.Delete.as_view(), name='issue_tag_delete'),

    # issue status
    url(r'^issue_statuses/$', issue_status.List.as_view(), name='issue_status_list'),
    url(r'^issue_statuses/add/$', issue_status.Create.as_view(), name='issue_status_add'),
    url(r'^issue_statuses/(?P<pk>\d+)/update/$', issue_status.Update.as_view(), name='issue_status_update'),
    url(r'^issue_statuses/(?P<pk>\d+)/delete/$', issue_status.Delete.as_view(), name='issue_status_delete'),

    # issue
    url(r'^projects/(?P<pk>\d+)/issues/$', issue.List.as_view(), name='issue_list'),
    url(r'^projects/(?P<pk>\d+)/issues/add/$', issue.Create.as_view(), name='issue_add'),
    url(r'^issues/(?P<pk>\d+)/$', issue.Detail.as_view(), name='issue_detail'),
    url(r'^issues/(?P<pk>\d+)/update/$', issue.Update.as_view(), name='issue_update'),
    url(r'^issues/(?P<pk>\d+)/delete/$', issue.Delete.as_view(), name='issue_delete'),
    url(r'^issues/(?P<pk>\d+)/quote/$', issue.Quote.as_view(), name='issue_quote'),
    url(r'^issues/(?P<pk>\d+)/watch/$', issue.Watch.as_view(), name='issue_watch'),
    url(r'^issues/(?P<pk>\d+)/unwatch/$', issue.Unwatch.as_view(), name='issue_unwatch'),
    url(r'^comments/(?P<pk>\d+)/update/$', issue.CommentUpdate.as_view(), name='comment_update'),
    url(r'^issues/$', issue.AllIssues.as_view(), name='issue_all'),
    url(r'^mypage/$', issue.MyPage.as_view(), name='my_page'),

    # worktime
    url(r'^issues/(?P<pk>\d+)/worktimes/$', issue.WorktimeList.as_view(), name='worktime_list'),
    url(r'^issues/(?P<pk>\d+)/worktimes/add$', issue.WorktimeCreate.as_view(), name='worktime_add'),
    url(r'^worktimes/(?P<pk>\d+)/update/$', issue.WorktimeUpdate.as_view(), name='worktime_update'),
    url(r'^worktimes/(?P<pk>\d+)/delete/$', issue.WorktimeDelete.as_view(), name='worktime_delete'),

    # version
    url(r'^projects/(?P<pk>\d+)/roadmap/$', version.Roadmap.as_view(), name='version_roadmap'),
    url(r'^projects/(?P<pk>\d+)/versions/add/$', version.Create.as_view(), name='version_add'),
    url(r'^versions/(?P<pk>\d+)/$', version.Detail.as_view(), name='version_detail'),
    url(r'^versions/(?P<pk>\d+)/update/$', version.Update.as_view(), name='version_update'),
    url(r'^versions/(?P<pk>\d+)/delete/$', version.Delete.as_view(), name='version_delete'),

    # user
    url(r'^users/$', user.List.as_view(), name='user_list'),
    url(r'^users/add/$', user.Create.as_view(), name='user_add'),
    url(r'^users/(?P<pk>\d+)/$', user.Detail.as_view(), name='user_detail'),
    url(r'^users/(?P<pk>\d+)/update/$', user.Update.as_view(), name='user_update'),
    url(r'^users/(?P<pk>\d+)/delete/$', user.Delete.as_view(), name='user_delete'),
    url(r'^users/(?P<pk>\d+)/lock/$', user.Lock.as_view(), name='user_lock'),
    url(r'^users/(?P<pk>\d+)/unlock/$', user.Unlock.as_view(), name='user_unlock'),
    url(r'^users/(?P<pk>\d+)/join_projects/$', user.JoinProjects.as_view(), name='user_join_projects'),
    url(r'^users/(?P<pk>\d+)/quit_project/(?P<id>\d+)$', user.QuitProject.as_view(), name='user_quit_project'),
    url(r'^users/(?P<pk>\d+)/join_groups/$', user.JoinGroups.as_view(), name='user_join_groups'),
    url(r'^users/(?P<pk>\d+)/quit_group/(?P<id>\d+)$', user.QuitGroup.as_view(), name='user_quit_group'),
    url(r'^users/(?P<pk>\d+)/projects/(?P<id>\d+)/roles$', user.Roles.as_view(), name='user_roles'),

    # group
    url(r'^groups/$', group.List.as_view(), name='group_list'),
    url(r'^groups/add/$', group.Create.as_view(), name='group_add'),
    url(r'^groups/(?P<pk>\d+)/update/$', group.Update.as_view(), name='group_update'),
    url(r'^groups/(?P<pk>\d+)/delete/$', group.Delete.as_view(), name='group_delete'),
    url(r'^groups/(?P<pk>\d+)/add_users/$', group.AddUsers.as_view(), name='group_add_users'),
    url(r'^groups/(?P<pk>\d+)/delete_user/(?P<id>\d+)$', group.DeleteUser.as_view(), name='group_delete_user'),
    url(r'^groups/(?P<pk>\d+)/join_projects/$', group.JoinProjects.as_view(), name='group_join_projects'),
    url(r'^groups/(?P<pk>\d+)/quit_project/(?P<id>\d+)$', group.QuitProject.as_view(), name='group_quit_project'),
    url(r'^groups/(?P<pk>\d+)/projects/(?P<id>\d+)/roles$', group.Roles.as_view(), name='group_roles'),

    # role
    url(r'^roles/$', role.List.as_view(), name='role_list'),
    url(r'^roles/add/$', role.Create.as_view(), name='role_add'),
    url(r'^roles/(?P<pk>\d+)/update/$', role.Update.as_view(), name='role_update'),
    url(r'^roles/(?P<pk>\d+)/delete/$', role.Delete.as_view(), name='role_delete'),

    # settings
    url(r'^settings/$', settings.Update.as_view(), name='settings'),
    url(r'^admin/$', project.Admin.as_view(), name='admin'),
    url(r'^admin/projects/$', project.Admin.as_view(), name='admin_project'),

    # status page
    url(r'^403/$', TemplateView.as_view(template_name="status/403.html"), name='status_403'),

    url(r'^django-admin/', include(admin.site.urls)),
]

src/apps/project/models.py
# coding:utf-8
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User


@python_2_unicode_compatible
class Project(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    homepage = models.CharField(max_length=255, default='', blank=True)
    is_public = models.BooleanField(default=True)
    parent_id = models.ForeignKey('Project', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    identifier = models.CharField(max_length=255, null=True, blank=True, unique=True)
    status = models.IntegerField(default=1)     # built-in: open,closed
    inherit_members = models.BooleanField(default=False)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Issue(models.Model):
    issue_type = models.ForeignKey('IssueType')
    project_id = models.ForeignKey('Project')
    subject = models.CharField(max_length=255, default='')
    description = models.TextField(null=True, blank=True)
    start_date = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    status = models.ForeignKey('IssueStatus')
    assigned_to = models.ForeignKey(User, null=True, blank=True)
    priority = models.IntegerField(default=1)       # built-in (low,normal,high,emergency,immediately)
    version = models.ForeignKey('Version', null=True, blank=True)
    author =  models.ForeignKey(User, related_name='created_by')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    done_ratio = models.IntegerField(default=0)
    parent_id = models.ForeignKey('Issue', null=True, blank=True)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.subject


@python_2_unicode_compatible
class IssueType(models.Model):
    name = models.CharField(max_length=30, default='', unique=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class IssueStatus(models.Model):
    name = models.CharField(max_length=30, default='', unique=True)
    default_done_ratio = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Version(models.Model):
    project = models.ForeignKey('Project')
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    wiki_page = models.CharField(max_length=255, null=True, blank=True)
    status = models.IntegerField(default=1)     # built-in (open,locked,closed)
    effective_date = models.DateTimeField()

    class Meta:
        unique_together = ("project", "name")

    def __str__(self):
        return self.name

src/pm/views/account.py
from django.views.generic import View
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User
from django.shortcuts import render
from ..forms import UserAccountForm, UploadAvatarForm
from ..models import Profile
from .base import UpdateSuccessMessageMixin, update_success_message
from .auth import LoginRequiredMixin
from django.conf import settings
import os
from PIL import Image


class MyAccount(LoginRequiredMixin, UpdateSuccessMessageMixin, UpdateView):
    model = User
    form_class = UserAccountForm
    template_name = 'my_account.html'
    success_url = reverse_lazy('my_account')

    def get_object(self, queryset=None):
        return self.request.user


class MyAvatar(LoginRequiredMixin, View):

    _AVATAR_MAX_WIDTH = 100
    _AVATAR_MAX_HEIGHT = 100

    def get(self, request, *args, **kwargs):
        form = UploadAvatarForm()
        return render(request, 'avatar.html', {'form': form})

    def handle_uploaded_file(self, f, name):
        ext = name.split(".")[-1].lower()
        new_name = '%s.%s' % (self.request.user.id, ext)
        dir = settings.UPLOAD_AVATAR_DIR
        path = os.path.join(dir, new_name)

        if not os.path.exists(dir):
            os.makedirs(dir)

        with open(path, 'wb+') as dest:
            for chunk in f.chunks():
                dest.write(chunk)
                dest.close()

        im = Image.open(path)
        width,height = im.size
        if width > self._AVATAR_MAX_WIDTH or height > self._AVATAR_MAX_HEIGHT:
            im.resize((self._AVATAR_MAX_WIDTH, self._AVATAR_MAX_HEIGHT)).save(path)

        p = Profile.objects.get_or_create(user=self.request.user)[0]
        p.avatar = new_name
        p.save()

    def post(self, request, *args, **kwargs):
        form = UploadAvatarForm(request.POST, request.FILES)
        if form.is_valid():
            self.handle_uploaded_file(request.FILES['file'], form.cleaned_data['file'].name)

            from django.contrib import messages
            messages.success(self.request, update_success_message % 'avatar')
        return render(request, 'avatar.html', {'form': form})

src/pm/views/base.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib import messages

create_success_message = '%s was created successfully.'
update_success_message = '%s was updated successfully.'
delete_success_message = '%s was deleted successfully.'


class homepage(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')


def decorate_object(obj):
    return '\"%s\"' % obj


class SuccessMessageMixin(object):
    success_message = ''

    def form_valid(self, form):
        response = super(SuccessMessageMixin, self).form_valid(form)
        success_message = self.get_success_message()
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self):
        return self.success_message


class CreateSuccessMessageMixin(SuccessMessageMixin):
    def get_success_message(self):
        return self.success_message or create_success_message % decorate_object(self.object)


class UpdateSuccessMessageMixin(SuccessMessageMixin):
    def get_success_message(self):
        return self.success_message or update_success_message % decorate_object(self.object)


class DeleteSuccessMessageMixin(object):
    def delete(self, request, *args, **kwargs):
        success_message = self.get_success_message()
        if success_message:
            messages.success(self.request, success_message)

        return super(DeleteSuccessMessageMixin, self).delete(request, *args, **kwargs)

    def get_success_message(self):
        return delete_success_message % decorate_object(self.get_object())

src/templates/all_issues.html
{% extends "base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block page-content %}
  <div class="portlet light bordered">
    <div class="portlet-title">
      <div class="caption">
        <span class="caption-subject font-green-sharp bold uppercase">所有问题</span>
      </div>
    </div>
    <div class="portlet-body">
      <div class="row">
        <div class="col-md-12">
          <div class="form-inline table-options">
            <div class="form-group">{{ form.project|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">{{ form.version|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">{{ form.tag|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">{{ form.status|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">{{ form.priority|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">{{ form.assignee|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">{{ form.watcher|add_class:"form-control issue-filter" }}</div>
            <div class="form-group">
              <div class="input-group input-large">
                {{ form.start_date|add_class:"form-control date-picker"|attr:"end-date:id_due_date"}}
                <span class="input-group-addon"> to </span>
                {{ form.due_date|add_class:"form-control date-picker"|attr:"start-date:id_start_date" }}
              </div>
            </div>
            <div class="form-group"><button class="form-control btn default" id="btn-view">View</button></div>
          </div>
          <div class="table-scrollable">
            <table class="table table-light table-advance table-hover table-condensed second">
              <thead>
              <tr>
                <th><a name="btn-order" orderby="id">ID</a></th>
                <th><a name="btn-order" orderby="project">项目</a></th>
                <th><a name="btn-order" orderby="version">版本</a></th>
                <th><a name="btn-order" orderby="tag">标签</a></th>
                <th><a name="btn-order" orderby="status">状态</a></th>
                <th><a name="btn-order" orderby="priority">优先级</a></th>
                <th><a name="btn-order" orderby="subject">主题</a></th>
                <th><a name="btn-order" orderby="assigned_to">指派给</a></th>
                <th><a name="btn-order" orderby="updated_on">更新于</a></th>
              </tr>
              </thead>
              <tbody>
                {% if issues %}
                  {% for issue in issues %}
                    <tr>
                      <td><a href="{% url 'issue_detail' issue.id %}">{{ issue.id }}</a></td>
                      <td><a href="{% url 'project_detail' issue.project.id %}">{{ issue.project.name }}</a></td>
                      <td>{% if issue.version %}<a href="{% url 'version_detail' issue.version.id %}">{{ issue.version.name }}</a>{% else %}-{% endif %}</td>
                      <td>{{ issue.tag|default:"-" }}</td>
                      <td>{{ issue.status|default:"-" }}</td>
                      <td>{{ issue.get_priority_display|default:"-" }}</td>
                      <td><a href="{% url 'issue_detail' issue.id %}">{{ issue.subject }}</a></td>
                      <td>{% if issue.assigned_to %}<a href="{% url 'user_detail' issue.assigned_to.id %}">{{ issue.assigned_to }}</a>{% else %}-{% endif %}</td>
                      <td>{{ issue.updated_on|date:'Y-m-d H:i:s' }}</td>
                    </tr>
                  {% endfor %}
                {% else %}
                  <tr>
                    <td colspan="8">{% include 'no_data.html' %}</td>
                  </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
          {% include 'table_paging.html' %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block page-level-scripts %}
<script>
  var page_url = '{% url 'issue_all' %}';

  function get_query_item(obj, name) {
      var value = obj.val();
      return (value) ? (name + "=" + value) : '';
  }

  function get_query_string() {
    var querystr = "";
    var items = [
        {% for field in form %}
          ["{{ field.auto_id }}", "{{ field.html_name }}"],
        {% endfor %}
    ];

    var first = true;
    for (var i=0; i<items.length; i++) {
      var item = items[i];
      var str = get_query_item($('#' + item[0]), item[1]);
      if (str) {
        querystr = querystr + ((first) ? '?' : '&') + str;
        first = false;
      }
    }
    return querystr;
  }

  init_table_orderby(page_url, get_query_string);

  $('#btn-view').click(function(){
    location = page_url + get_query_string();
  });
</script>
{% endblock %}

src/templates/avatar.html
{% extends "base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block page-content %}
  <div class="portlet light bordered">
    <div class="portlet-title">
      <div class="caption">
        <span class="caption-subject font-green-sharp bold uppercase">修改头像</span>
      </div>
    </div>
    <div class="portlet-body">
      {% include 'form_success.html' %}
      <div class="portlet light grey-cararra bordered">
        <div class="portlet-body form">
          {% include 'form_errors.html' %}
          <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-body">
              <div class="row">
                <div class="col-md-12 col-md-offset-3">
                  <div class="form-group">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                        <img src="/static/img/menu-toggler.png" alt=""/>
                      </div>
                      <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                      <div>
                        <span class="btn default btn-file">
                          <span class="fileinput-new">Select image</span>
                          <span class="fileinput-exists">Change</span>
                          <!--<input type="file" name="avata">-->
                          {{ form.file|add_class:"form-control" }}
                        </span>
                        <a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput">Remove</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-actions">
              <div class="row">
                <div class="col-md-offset-3">
                  <button type="submit" class="btn green">保存</button>
                  <a href="{% url 'my_account' %}" class="btn default">返回</a>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/confirm_delete.html
<div id="confirm-delete" class="modal" tabindex="-1" data-width="500">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <h4>Are you sure?</h4>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <form method="post">
          {% csrf_token %}
          <button type="button" data-dismiss="modal" class="btn btn-default">Close</button>
          <button type="submit" class="btn red">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

src/templates/create_project.html
{% extends "base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block page-content %}
  <div class="portlet light bordered">
    <div class="portlet-title">
      <div class="caption">
        <span class="caption-subject font-green-sharp bold uppercase">{% trans 'Create Project' %}</span>
      </div>
    </div>
    <div class="portlet-body">
      <div class="portlet light grey-cararra bordered">
        <div class="portlet-body form">
          {% include 'project_form.html' %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/form_errors.html
{% if form.errors %}
  <div class="alert alert-danger">
    <ul class="message error">
      {% for key, value in form.errors.items %}
        {% for error in value %}
          <li>{{ key|title }} - {{ error|title }}</li>
        {% endfor %}
      {% endfor %}
    </ul>
  </div>
{% endif %}

src/templates/form_success.html
{% if messages %}
  <div class="alert alert-success">
    <ul class="message success">
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

src/templates/my_page.html
{% extends "base.html" %}


{% block page-content %}
  <div class="row">
    <div class="col-md-12">
      <div class="portlet light bordered">
        <div class="portlet-title">
          <div class="caption">
            <span class="caption-subject font-green-sharp bold uppercase">我的工作台</span>
          </div>
        </div>
        <div class="portlet-body">
          <div class="row">
            <div class="col-md-6">
              <div class="portlet box">
                <div class="portlet-body">
                  <div class="table-caption">
                    <span>指派给我的问题 ({{ assigned_issues|length }})</span>
                    {% if assigned_issues %}
                      <small class="pull-right"><a href="{% url 'issue_all' %}?assignee={{ user.id }}">更多»</a></small>
                    {% endif %}
                  </div>
                  <div class="table-scrollable">
                    <table class="table table-light table-advance table-hover table-condensed second">
                      <thead>
                      <tr>
                        <th>#</th>
                        <th>项目</th>
                        <th>标签</th>
                        <th>主题</th>
                      </tr>
                      </thead>
                      <tbody>
                      {% if assigned_issues %}
                      {% for issue in assigned_issues %}
                        <tr>
                          <td>{{ issue.id }}</td>
                          <td><a href="{% url 'project_detail' issue.project.id %}">{{ issue.project.name }}</a></td>
                          <td>{{ issue.tag }}</td>
                          <td><a href="{% url 'issue_detail' issue.id %}">{{ issue.subject }}</a></td>
                        </tr>
                      {% endfor %}
                      {% else %}
                        <tr>
                          <td colspan="4">{% include 'no_data.html' %}</td>
                        </tr>
                      {% endif %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="portlet box">
                <div class="portlet-body">
                  <div class="table-caption">
                    <span>我关注的问题 ({{ watch_issues|length }})</span>
                    {% if watch_issues %}
                      <small class="pull-right"><a href="{% url 'issue_all' %}?watcher={{ user.id }}">更多»</a></small>
                    {% endif %}
                  </div>
                  <div class="table-scrollable">
                    <table class="table table-light table-advance table-hover table-condensed second">
                      <thead>
                      <tr>
                        <th>#</th>
                        <th>项目</th>
                        <th>标签</th>
                        <th>主题</th>
                      </tr>
                      </thead>
                      <tbody>
                      {% if watch_issues %}
                        {% for issue in watch_issues %}
                          <tr>
                            <td>{{ issue.id }}</td>
                            <td><a href="{% url 'project_detail' issue.project.id %}">{{ issue.project.name }}</a></td>
                            <td>{{ issue.tag }}</td>
                            <td><a href="{% url 'issue_detail' issue.id %}">{{ issue.subject }}</a></td>
                          </tr>
                        {% endfor %}
                      {% else %}
                        <tr>
                          <td colspan="4">{% include 'no_data.html' %}</td>
                        </tr>
                      {% endif %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/no_data.html
<div class="nodata"><span>暂无数据可显示</span></div>

src/templates/project_list.html
{% extends "base.html" %}

{% load i18n %}
{% load permission_tags %}

{% block page-content %}
  <div class="row">
    <div class="col-md-12">
      <div class="portlet light bordered">
        <div class="portlet-title">
          <div class="caption">
            <span class="caption-subject font-green-sharp bold">{% trans 'Projects' %}</span>
          </div>
          <div class="actions btn-set">
            {% if perms.pm.add_project %}
              <a type="button" class="btn btn-default btn-circle" href="{% url 'project_add' %}"><i class="fa fa-plus"></i> 新建项目</a>
            {% endif %}
            <a class="btn btn-default btn-circle" href="{% url 'issue_all' %}"> 查看所有问题</a>
          </div>
        </div>
        <div class="portlet-body">
          {% include 'form_success.html' %}
          <div id="my-project"><i class="fa fa-user"></i>joined<br/><i class="fa fa-lock"></i>private</div>
          <div class="project-list">
            {% if projects %}
              {{ projects|safe }}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}