src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from pm.views import user, project, issue, issue_status, issue_tag, version, group, role, settings, \
    issue_category, base, account

urlpatterns = [
    url(r'^$', base.homepage.as_view(), name='homepage'),

    # authentication
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^my/password$', auth_views.password_change,
        {'template_name': 'password.html', 'post_change_redirect': '/my/password'}, name='password_change'),

    # account
    url(r'^my/account$', account.MyAccount.as_view(), name='my_account'),
    url(r'^my/avatar$', account.MyAvatar.as_view(), name='my_avatar'),

    # project
    url(r'^projects/$', project.List.as_view(), name='project_list'),
    url(r'^projects/(?P<pk>\d+)/$', project.Detail.as_view(), name='project_detail'),
    url(r'^projects/add/$', project.Create.as_view(), name='project_add'),
    url(r'^projects/(?P<pk>\d+)/delete/$', project.Delete.as_view(), name='project_delete'),
    url(r'^projects/(?P<pk>\d+)/close/$', project.Close.as_view(), name='project_close'),
    url(r'^projects/(?P<pk>\d+)/reopen/$', project.Reopen.as_view(), name='project_reopen'),
    url(r'^projects/(?P<pk>\d+)/gantt/$', project.Gantt.as_view(), name='project_gantt'),

    # project settings
    url(r'^projects/(?P<pk>\d+)/settings/$', project.Settings.as_view(), name='project_settings'),
    url(r'^projects/(?P<pk>\d+)/settings/info/$', project.Update.as_view(), name='project_update'),
    url(r'^projects/(?P<pk>\d+)/settings/versions/$', version.List.as_view(), name='version_list'),
    url(r'^projects/(?P<pk>\d+)/settings/members/$', project.ListMember.as_view(), name='member_list'),
    url(r'^projects/(?P<pk>\d+)/settings/issue_categories/$', issue_category.List.as_view(), name='issue_category_list'),

    # member
    url(r'^projects/(?P<pk>\d+)/members/delete$', project.DeleteMember.as_view(), name='member_delete'),
    url(r'^projects/(?P<pk>\d+)/members/add$', project.CreateMember.as_view(), name='member_add'),
    url(r'^projects/(?P<pk>\d+)/members/roles$', project.MemberRoles.as_view(), name='member_roles'),

    # issue category
    url(r'^projects/(?P<pk>\d+)/issue_categories/add/$', issue_category.Create.as_view(), name='issue_category_add'),
    url(r'^issue_categories/(?P<pk>\d+)/update/$', issue_category.Update.as_view(), name='issue_category_update'),
    url(r'^issue_categories/(?P<pk>\d+)/delete/$', issue_category.Delete.as_view(), name='issue_category_delete'),

    # issue tag
    url(r'^issue_tags/$', issue_tag.List.as_view(), name='issue_tag_list'),
    url(r'^issue_tags/add/$', issue_tag.Create.as_view(), name='issue_tag_add'),
    url(r'^issue_tags/(?P<pk>\d+)/update/$', issue_tag.Update.as_view(), name='issue_tag_update'),
    url(r'^issue_tags/(?P<pk>\d+)/delete/$', issue_tag.Delete.as_view(), name='issue_tag_delete'),

    # issue status
    url(r'^issue_statuses/$', issue_status.List.as_view(), name='issue_status_list'),
    url(r'^issue_statuses/add/$', issue_status.Create.as_view(), name='issue_status_add'),
    url(r'^issue_statuses/(?P<pk>\d+)/update/$', issue_status.Update.as_view(), name='issue_status_update'),
    url(r'^issue_statuses/(?P<pk>\d+)/delete/$', issue_status.Delete.as_view(), name='issue_status_delete'),

    # issue
    url(r'^projects/(?P<pk>\d+)/issues/$', issue.List.as_view(), name='issue_list'),
    url(r'^projects/(?P<pk>\d+)/issues/add/$', issue.Create.as_view(), name='issue_add'),
    url(r'^issues/(?P<pk>\d+)/$', issue.Detail.as_view(), name='issue_detail'),
    url(r'^issues/(?P<pk>\d+)/update/$', issue.Update.as_view(), name='issue_update'),
    url(r'^issues/(?P<pk>\d+)/delete/$', issue.Delete.as_view(), name='issue_delete'),
    url(r'^issues/(?P<pk>\d+)/quote/$', issue.Quote.as_view(), name='issue_quote'),
    url(r'^issues/(?P<pk>\d+)/watch/$', issue.Watch.as_view(), name='issue_watch'),
    url(r'^issues/(?P<pk>\d+)/unwatch/$', issue.Unwatch.as_view(), name='issue_unwatch'),
    url(r'^comments/(?P<pk>\d+)/update/$', issue.CommentUpdate.as_view(), name='comment_update'),
    url(r'^issues/$', issue.AllIssues.as_view(), name='issue_all'),
    url(r'^mypage/$', issue.MyPage.as_view(), name='my_page'),

    # worktime
    url(r'^issues/(?P<pk>\d+)/worktimes/$', issue.WorktimeList.as_view(), name='worktime_list'),
    url(r'^issues/(?P<pk>\d+)/worktimes/add$', issue.WorktimeCreate.as_view(), name='worktime_add'),
    url(r'^worktimes/(?P<pk>\d+)/update/$', issue.WorktimeUpdate.as_view(), name='worktime_update'),
    url(r'^worktimes/(?P<pk>\d+)/delete/$', issue.WorktimeDelete.as_view(), name='worktime_delete'),

    # version
    url(r'^projects/(?P<pk>\d+)/roadmap/$', version.Roadmap.as_view(), name='version_roadmap'),
    url(r'^projects/(?P<pk>\d+)/versions/add/$', version.Create.as_view(), name='version_add'),
    url(r'^versions/(?P<pk>\d+)/$', version.Detail.as_view(), name='version_detail'),
    url(r'^versions/(?P<pk>\d+)/update/$', version.Update.as_view(), name='version_update'),
    url(r'^versions/(?P<pk>\d+)/delete/$', version.Delete.as_view(), name='version_delete'),

    # user
    url(r'^users/$', user.List.as_view(), name='user_list'),
    url(r'^users/add/$', user.Create.as_view(), name='user_add'),
    url(r'^users/(?P<pk>\d+)/$', user.Detail.as_view(), name='user_detail'),
    url(r'^users/(?P<pk>\d+)/update/$', user.Update.as_view(), name='user_update'),
    url(r'^users/(?P<pk>\d+)/delete/$', user.Delete.as_view(), name='user_delete'),
    url(r'^users/(?P<pk>\d+)/lock/$', user.Lock.as_view(), name='user_lock'),
    url(r'^users/(?P<pk>\d+)/unlock/$', user.Unlock.as_view(), name='user_unlock'),
    url(r'^users/(?P<pk>\d+)/join_projects/$', user.JoinProjects.as_view(), name='user_join_projects'),
    url(r'^users/(?P<pk>\d+)/quit_project/(?P<id>\d+)$', user.QuitProject.as_view(), name='user_quit_project'),
    url(r'^users/(?P<pk>\d+)/join_groups/$', user.JoinGroups.as_view(), name='user_join_groups'),
    url(r'^users/(?P<pk>\d+)/quit_group/(?P<id>\d+)$', user.QuitGroup.as_view(), name='user_quit_group'),
    url(r'^users/(?P<pk>\d+)/projects/(?P<id>\d+)/roles$', user.Roles.as_view(), name='user_roles'),

    # group
    url(r'^groups/$', group.List.as_view(), name='group_list'),
    url(r'^groups/add/$', group.Create.as_view(), name='group_add'),
    url(r'^groups/(?P<pk>\d+)/update/$', group.Update.as_view(), name='group_update'),
    url(r'^groups/(?P<pk>\d+)/delete/$', group.Delete.as_view(), name='group_delete'),
    url(r'^groups/(?P<pk>\d+)/add_users/$', group.AddUsers.as_view(), name='group_add_users'),
    url(r'^groups/(?P<pk>\d+)/delete_user/(?P<id>\d+)$', group.DeleteUser.as_view(), name='group_delete_user'),
    url(r'^groups/(?P<pk>\d+)/join_projects/$', group.JoinProjects.as_view(), name='group_join_projects'),
    url(r'^groups/(?P<pk>\d+)/quit_project/(?P<id>\d+)$', group.QuitProject.as_view(), name='group_quit_project'),
    url(r'^groups/(?P<pk>\d+)/projects/(?P<id>\d+)/roles$', group.Roles.as_view(), name='group_roles'),

    # role
    url(r'^roles/$', role.List.as_view(), name='role_list'),
    url(r'^roles/add/$', role.Create.as_view(), name='role_add'),
    url(r'^roles/(?P<pk>\d+)/update/$', role.Update.as_view(), name='role_update'),
    url(r'^roles/(?P<pk>\d+)/delete/$', role.Delete.as_view(), name='role_delete'),

    # settings
    url(r'^settings/$', settings.Update.as_view(), name='settings'),
    url(r'^admin/$', project.Admin.as_view(), name='admin'),
    url(r'^admin/projects/$', project.Admin.as_view(), name='admin_project'),

    # status page
    url(r'^403/$', TemplateView.as_view(template_name="status/403.html"), name='status_403'),

    url(r'^django-admin/', include(admin.site.urls)),
]

src/pm/models.py
# coding:utf-8
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils.translation import ugettext as _
from django.core.validators import MinValueValidator
from datetime import datetime

_STRING_MAX_LENGTH = 255


def _get_estimated_time(issues):
    n = 0
    for issue in issues:
        if issue.start_date and issue.due_date and issue.start_date <= issue.due_date:
            n += (issue.due_date - issue.start_date).days + 1
    return n * 8


@python_2_unicode_compatible
class User(AbstractUser):
    def __str__(self):
        # TODO: formatted by settings
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip() or self.username


@python_2_unicode_compatible
class Project(models.Model):

    class Meta:
        default_permissions = ()

        # put all permissions here.
        permissions = (
            ("change_project", "Change project"),
            ("close_project", "Close project"),

            ("read_member", "Read member"),
            ("manage_member", "Manage member"),

            ("read_version", "Read version"),
            ("manage_version", "Manage version"),

            ("manage_issue_category", "Manage issue category"),

            ("read_gantt", "Read Gantt"),

            ("read_issue", "Read issue"),
            ("add_issue", "Add issue"),
            ("change_issue", "Change issue"),
            ("change_assigned_issue", "Change assigned issue"),
            ("delete_issue", "Delete issue"),
            ("delete_own_issue", "Delete own issue"),

            ("read_comment", "Read comment"),
            ("add_comment", "Add comment"),
            ("change_comment", "Change comment"),
            ("change_own_comment", "Change own comment"),
            ("delete_comment", "Delete comment"),
            ("delete_own_comment", "Delete own comment"),

            ("read_worktime", "Read worktime"),
            ("add_worktime", "Add worktime"),
            ("change_worktime", "Change worktime"),
            ("change_own_worktime", "Change own worktime"),
            ("delete_worktime", "Delete worktime"),
            ("delete_own_worktime", "Delete own worktime"),
        )

    OPEN_STATUS = 1
    CLOSED_STATUS = 2

    STATUS_CHOICES = (
        (OPEN_STATUS, _('open')),
        (CLOSED_STATUS, _('closed')),
    )

    name = models.CharField(max_length=_STRING_MAX_LENGTH, unique=True)
    description = models.TextField(null=True, blank=True)
    homepage = models.CharField(max_length=_STRING_MAX_LENGTH, default='', blank=True)
    is_public = models.BooleanField(default=True)
    parent = models.ForeignKey('Project', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    identifier = models.CharField(max_length=255, null=True, blank=True, unique=True)
    status = models.IntegerField(default=OPEN_STATUS, choices=STATUS_CHOICES)
    inherit_members = models.BooleanField(default=False)
    created_by = models.ForeignKey('User', related_name='creator')

    def __str__(self):
        return self.name

    def issue_report(self):
        issues = Issue.objects.filter(project=self)

        import collections
        data = collections.defaultdict(dict)
        for issue in issues:
            if Version.STATUS_CHOICES[Version.CLOSED_STATUS-1][1] == issue.status.name:
                data[issue.tag]['closed'] = data[issue.tag].get('closed', 0) + 1
            else:
                data[issue.tag]['open'] = data[issue.tag].get('open', 0) + 1

        for key, value in data.iteritems():
            data[key]['total'] = data[key].get('open', 0) + data[key].get('closed', 0)

        return dict(data)

    def estimated_time(self):
        return _get_estimated_time(Issue.objects.filter(project=self))

    def spent_time(self):
        return Issue.objects.filter(project=self).aggregate(hours=models.Sum('worktime__hours'))['hours'] or 0

    issue_report = property(issue_report)
    estimated_time = property(estimated_time)
    spent_time = property(spent_time)


@python_2_unicode_compatible
class Issue(models.Model):

    class Meta:
        default_permissions = ()

    LOW_PRIORITY = 1
    NORMAL_PRIORITY = 2
    HIGH_PRIORITY = 3
    EMERGENCY_PRIORITY = 4
    IMMEDIATELY_PRIORITY = 5

    PRIORITY_CHOICES = (
        (LOW_PRIORITY, _('Low')),
        (NORMAL_PRIORITY, _('Normal')),
        (HIGH_PRIORITY, _('High')),
        (EMERGENCY_PRIORITY, _('Emergency')),
        (IMMEDIATELY_PRIORITY, _('Immediately')),
    )

    DONE_RATIO_CHOICES = tuple((n, str(n)+"%") for n in range(0, 101, 10))

    tag = models.ForeignKey('IssueTag')
    category = models.ForeignKey('IssueCategory', null=True, blank=True)
    project = models.ForeignKey('Project')
    subject = models.CharField(max_length=_STRING_MAX_LENGTH)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    status = models.ForeignKey('IssueStatus')
    assigned_to = models.ForeignKey('User', null=True, blank=True)
    priority = models.IntegerField(default=NORMAL_PRIORITY, choices=PRIORITY_CHOICES)
    version = models.ForeignKey('Version', null=True, blank=True)
    author = models.ForeignKey('User', related_name='created_by')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    done_ratio = models.IntegerField(default=0, choices=DONE_RATIO_CHOICES)
    parent = models.ForeignKey('Issue', null=True, blank=True)
    is_private = models.BooleanField(default=False)
    watchers = models.ManyToManyField('User', related_name='watchers')

    def __str__(self):
        return self.subject


@python_2_unicode_compatible
class IssueCategory(models.Model):
    name = models.CharField(max_length=_STRING_MAX_LENGTH)
    project = models.ForeignKey('Project')

    class Meta:
        default_permissions = ()
        unique_together = ("project", "name")

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class IssueTag(models.Model):

    BUG_TAG = 1
    DEVELOPMENT_TAG = 2
    REQUIREMENT_TAG = 3

    INITIAL_DATA = (
        (BUG_TAG, _('Bug')),
        (DEVELOPMENT_TAG, _('Development')),
        (REQUIREMENT_TAG, _('Requirement')),
    )

    UNDELETABLE = ()

    name = models.CharField(max_length=_STRING_MAX_LENGTH, unique=True)

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class IssueStatus(models.Model):

    NEW_STATUS = 1
    FINISHED_STATUS = 2
    CLOSED_STATUS = 3
    NOT_CLOSED_STATUS = -CLOSED_STATUS

    INITIAL_DATA = (
        (NEW_STATUS, _('New')),
        (FINISHED_STATUS, _('Finished')),
        (CLOSED_STATUS, _('Closed')),
    )

    UNDELETABLE = (NEW_STATUS, FINISHED_STATUS, CLOSED_STATUS)

    name = models.CharField(max_length=_STRING_MAX_LENGTH, unique=True)
    # default_done_ratio = models.IntegerField(null=True, blank=True)

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Version(models.Model):

    OPEN_STATUS = 1
    LOCKED_STATUS = 2
    CLOSED_STATUS = 3

    STATUS_CHOICES = (
        (OPEN_STATUS, _('open')),
        (LOCKED_STATUS, _('locked')),
        (CLOSED_STATUS, _('closed')),
    )

    project = models.ForeignKey('Project')
    name = models.CharField(max_length=_STRING_MAX_LENGTH)
    description = models.CharField(max_length=_STRING_MAX_LENGTH, default="", blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    wiki_page = models.CharField(max_length=_STRING_MAX_LENGTH, default="", blank=True)
    status = models.IntegerField(default=OPEN_STATUS, choices=STATUS_CHOICES)
    effective_date = models.DateField(null=True, blank=True)

    class Meta:
        default_permissions = ()
        unique_together = ("project", "name")

    def total_issue(self):
        return Issue.objects.filter(version=self).count()

    def total_open_issue(self):
        return Issue.objects.filter(version=self).exclude(status__id=IssueStatus.CLOSED_STATUS).count()

    def total_closed_issue(self):
        return Issue.objects.filter(version=self).filter(status__id=IssueStatus.CLOSED_STATUS).count()

    def issues(self):
        return Issue.objects.filter(version=self)

    def done_ratio(self):
        return int(Issue.objects.filter(version=self)
                   .exclude(status__id=IssueStatus.CLOSED_STATUS)
                   .aggregate(data=models.Avg('done_ratio'))['data'])

    def estimated_time(self):
        return _get_estimated_time(Issue.objects.filter(version=self))

    def spent_time(self):
        return Issue.objects.filter(version=self).aggregate(hours=models.Sum('worktime__hours'))['hours'] or 0

    total_issue = property(total_issue)
    total_open_issue = property(total_open_issue)
    total_closed_issue = property(total_closed_issue)
    issues = property(issues)
    done_ratio = property(done_ratio)
    estimated_time = property(estimated_time)
    spent_time = property(spent_time)

    def __str__(self):
        return self.name


class Project_User_Role(models.Model):
    project = models.ForeignKey('Project')
    user = models.ForeignKey('User')
    role = models.ForeignKey('Role')
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        default_permissions = ()
        unique_together = ('project', 'user', 'role')


class Project_Group_Role(models.Model):
    project = models.ForeignKey('Project')
    group = models.ForeignKey(Group)
    role = models.ForeignKey('Role')
    created_on = models.DateTimeField(auto_now_add=True)

src/templates/_admin/create_group.html
{% extends "_admin/base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block tab_toggle %}tab_groups{% endblock %}

{% block tab_content %}
  {% include 'form_success.html' %}
  <div class="page-title">新建组</div>
  <div class="portlet-body">
    <div class="portlet light grey-cararra bordered">
      <div class="portlet-body form">
        {% include 'form_errors.html' %}
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          <div class="form-body">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label col-md-2">名称<span class="required">*</span></label>
                  <div class="col-md-4">
                    {{ form.name|add_class:"form-control" }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-2">
                <button type="submit" class="btn green" name="commit">创建</button>
                <button type="submit" class="btn green" name="continue">创建并继续</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/_admin/create_issue_status.html
{% extends "_admin/base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block tab_toggle %}tab_issue_statuses{% endblock %}


{% block tab_content %}
  {% include 'form_success.html' %}
  <div class="page-title">问题状态 >> 新建</div>
  <div class="portlet-body">
    <div class="portlet light grey-cararra bordered">
      <div class="portlet-body form">
        {% include 'form_errors.html' %}
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          <div class="form-body">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label col-md-2">名称<span class="required" aria-required="true">*</span></label>
                  <div class="col-md-4">
                    {{ form.name|add_class:"form-control" }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-2">
                <button type="submit" class="btn green" name="commit">创建</button>
                <button type="submit" class="btn green" name="continue">创建并继续</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/_admin/delete_project.html
{% extends "base.html" %}

{% load i18n %}

{% block page-content %}
  <div class="portlet light bordered" xmlns="http://www.w3.org/1999/html">
    <div class="portlet-title">
      <div class="caption">
        <span class="caption-subject font-green-sharp bold">{% trans 'Confirm' %}</span>
      </div>
    </div>
    <div class="portlet-body">
      <div class="alert alert-block alert-danger fade in confirm">
        <form method="post">
          {% csrf_token %}
          <p>{{ project.name }}</p>
          <p>{% trans 'Are you sure you want to delete this project and related data?' %}</p>
          <p>
            <button type="submit" class="btn red">{% trans 'Delete' %}</button>
            <a href="{% url 'admin_project' %}" class="btn grey-cascade">{% trans 'Cancel' %}</a>
          </p>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/_admin/edit_issue_tag.html
{% extends "_admin/base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block tab_toggle %}tab_issue_tags{% endblock %}


{% block tab_content %}
  {% include 'form_success.html' %}
  <div class="page-title">问题标签 >> 编辑</div>
  <div class="portlet-body">
    <div class="portlet light grey-cararra bordered">
      <div class="portlet-body form">
        {% include 'form_errors.html' %}
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          <div class="form-body">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label col-md-2">名称<span class="required" aria-required="true">*</span></label>
                  <div class="col-md-4">
                    {{ form.name|add_class:"form-control" }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-2">
                <button type="submit" class="btn green" name="commit">保存</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/_admin/edit_role.html
{% extends "_admin/base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block tab_toggle %}tab_roles{% endblock %}

{% block tab_content %}
  {% include 'form_success.html' %}
  <div class="page-title">编辑角色 >> {{ role.name }}</div>
  <div class="portlet-body">
    <div class="portlet light grey-cararra bordered">
      <div class="portlet-body form">
        {% include 'form_errors.html' %}
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          <div class="form-body">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label col-md-2">名称<span class="required" aria-required="true">*</span></label>
                  <div class="col-md-4">
                    {{ form.name|add_class:"form-control" }}
                  </div>
                </div>
                <h4 class="form-section">权限</h4>
                <div class="row">
                  {% for choice in form.permissions.field.choices %}
                    <div class="col-md-3">
                      <div class="icheck-inline">
                        <label><input type="checkbox" name="permissions" value="{{ choice.0 }}" {% if choice.0 in form.permissions.value %}checked{% endif %}>{{ choice.1 }}</label>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-2">
                <button type="submit" class="btn green" name="commit">保存</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/_admin/edit_tracker.html
{% extends "_admin/base.html" %}

{% block tab_toggle %}tab_trackers{% endblock %}


{% block tab_content %}
  <div class="page-title">跟踪标签 >> 研发</div>
  <div class="portlet-body">
    <div class="portlet light grey-cararra bordered">
      <div class="portlet-body form">
        <form action="javascript:;" class="form-horizontal">
          <div class="form-body">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="control-label col-md-2">名称<span class="required" aria-required="true">*</span></label>
                  <div class="col-md-4">
                    <input type="text" class="form-control" value="研发">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-2">
                <button type="submit" class="btn green" name="commit">保存</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/_admin/groups.html
{% extends "_admin/base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block tab_toggle %}tab_groups{% endblock %}

{% block tab_content %}
  {% include 'form_success.html' %}
  <div class="page-title">组</div>
  <div class="actions btn-set small btn-table">
    <a href="{% url 'group_add' %}"><i class="fa fa-plus">新建组</i></a>
  </div>
  {% if groups %}
    <div class="dataTables_wrapper">
      <div class="table-scrollable">
        <table class="table table-light table-advance table-hover table-condensed second">
          <thead>
          <tr>
            <th><a name="btn-order" orderby="name">组</a></th>
            <th>用户</th>
            <th width="110px"></th>
          </tr>
          </thead>
          <tbody>
          {% for group in groups %}
            <tr>
              <td><a href="{% url 'group_update' group.id %}">{{ group.name }}</a></td>
              <td>{{ group.user_set.count }}</td>
              <td>
                <div class="actions btn-set small">
                  <a data-href="{% url 'group_delete' group.id %}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash-o"></i>删除</a>
                </div>
              </td>
            </tr>
          {% endfor %}
          </tbody>
       </table>
      </div>
      {% include "table_paging.html" %}
    </div>
  {% else %}
    {% include 'no_data.html' %}
  {% endif %}

  {% include 'confirm_delete.html' %}
{% endblock %}

{% block page-level-scripts %}
<script>
  var page_url = '{% url 'group_list' %}';
  init_table_orderby(page_url, null);
</script>
{% endblock %}