src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from pm.views import user, project, issue, issue_status, issue_tag, version, group, role, settings, \
    issue_category, base, account

urlpatterns = [
    url(r'^$', base.homepage.as_view(), name='homepage'),

    # authentication
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^my/password$', auth_views.password_change,
        {'template_name': 'password.html', 'post_change_redirect': '/my/password'}, name='password_change'),

    # account
    url(r'^my/account$', account.MyAccount.as_view(), name='my_account'),
    url(r'^my/avatar$', account.MyAvatar.as_view(), name='my_avatar'),

    # project
    url(r'^projects/$', project.List.as_view(), name='project_list'),
    url(r'^projects/(?P<pk>\d+)/$', project.Detail.as_view(), name='project_detail'),
    url(r'^projects/add/$', project.Create.as_view(), name='project_add'),
    url(r'^projects/(?P<pk>\d+)/delete/$', project.Delete.as_view(), name='project_delete'),
    url(r'^projects/(?P<pk>\d+)/close/$', project.Close.as_view(), name='project_close'),
    url(r'^projects/(?P<pk>\d+)/reopen/$', project.Reopen.as_view(), name='project_reopen'),
    url(r'^projects/(?P<pk>\d+)/gantt/$', project.Gantt.as_view(), name='project_gantt'),

    # project settings
    url(r'^projects/(?P<pk>\d+)/settings/$', project.Settings.as_view(), name='project_settings'),
    url(r'^projects/(?P<pk>\d+)/settings/info/$', project.Update.as_view(), name='project_update'),
    url(r'^projects/(?P<pk>\d+)/settings/versions/$', version.List.as_view(), name='version_list'),
    url(r'^projects/(?P<pk>\d+)/settings/members/$', project.ListMember.as_view(), name='member_list'),
    url(r'^projects/(?P<pk>\d+)/settings/issue_categories/$', issue_category.List.as_view(), name='issue_category_list'),

    # member
    url(r'^projects/(?P<pk>\d+)/members/delete$', project.DeleteMember.as_view(), name='member_delete'),
    url(r'^projects/(?P<pk>\d+)/members/add$', project.CreateMember.as_view(), name='member_add'),
    url(r'^projects/(?P<pk>\d+)/members/roles$', project.MemberRoles.as_view(), name='member_roles'),

    # issue category
    url(r'^projects/(?P<pk>\d+)/issue_categories/add/$', issue_category.Create.as_view(), name='issue_category_add'),
    url(r'^issue_categories/(?P<pk>\d+)/update/$', issue_category.Update.as_view(), name='issue_category_update'),
    url(r'^issue_categories/(?P<pk>\d+)/delete/$', issue_category.Delete.as_view(), name='issue_category_delete'),

    # issue tag
    url(r'^issue_tags/$', issue_tag.List.as_view(), name='issue_tag_list'),
    url(r'^issue_tags/add/$', issue_tag.Create.as_view(), name='issue_tag_add'),
    url(r'^issue_tags/(?P<pk>\d+)/update/$', issue_tag.Update.as_view(), name='issue_tag_update'),
    url(r'^issue_tags/(?P<pk>\d+)/delete/$', issue_tag.Delete.as_view(), name='issue_tag_delete'),

    # issue status
    url(r'^issue_statuses/$', issue_status.List.as_view(), name='issue_status_list'),
    url(r'^issue_statuses/add/$', issue_status.Create.as_view(), name='issue_status_add'),
    url(r'^issue_statuses/(?P<pk>\d+)/update/$', issue_status.Update.as_view(), name='issue_status_update'),
    url(r'^issue_statuses/(?P<pk>\d+)/delete/$', issue_status.Delete.as_view(), name='issue_status_delete'),

    # issue
    url(r'^projects/(?P<pk>\d+)/issues/$', issue.List.as_view(), name='issue_list'),
    url(r'^projects/(?P<pk>\d+)/issues/add/$', issue.Create.as_view(), name='issue_add'),
    url(r'^issues/(?P<pk>\d+)/$', issue.Detail.as_view(), name='issue_detail'),
    url(r'^issues/(?P<pk>\d+)/update/$', issue.Update.as_view(), name='issue_update'),
    url(r'^issues/(?P<pk>\d+)/delete/$', issue.Delete.as_view(), name='issue_delete'),
    url(r'^issues/(?P<pk>\d+)/quote/$', issue.Quote.as_view(), name='issue_quote'),
    url(r'^issues/(?P<pk>\d+)/watch/$', issue.Watch.as_view(), name='issue_watch'),
    url(r'^issues/(?P<pk>\d+)/unwatch/$', issue.Unwatch.as_view(), name='issue_unwatch'),
    url(r'^comments/(?P<pk>\d+)/update/$', issue.CommentUpdate.as_view(), name='comment_update'),
    url(r'^issues/$', issue.AllIssues.as_view(), name='issue_all'),
    url(r'^mypage/$', issue.MyPage.as_view(), name='my_page'),

    # worktime
    url(r'^issues/(?P<pk>\d+)/worktimes/$', issue.WorktimeList.as_view(), name='worktime_list'),
    url(r'^issues/(?P<pk>\d+)/worktimes/add$', issue.WorktimeCreate.as_view(), name='worktime_add'),
    url(r'^worktimes/(?P<pk>\d+)/update/$', issue.WorktimeUpdate.as_view(), name='worktime_update'),
    url(r'^worktimes/(?P<pk>\d+)/delete/$', issue.WorktimeDelete.as_view(), name='worktime_delete'),

    # version
    url(r'^projects/(?P<pk>\d+)/roadmap/$', version.Roadmap.as_view(), name='version_roadmap'),
    url(r'^projects/(?P<pk>\d+)/versions/add/$', version.Create.as_view(), name='version_add'),
    url(r'^versions/(?P<pk>\d+)/$', version.Detail.as_view(), name='version_detail'),
    url(r'^versions/(?P<pk>\d+)/update/$', version.Update.as_view(), name='version_update'),
    url(r'^versions/(?P<pk>\d+)/delete/$', version.Delete.as_view(), name='version_delete'),

    # user
    url(r'^users/$', user.List.as_view(), name='user_list'),
    url(r'^users/add/$', user.Create.as_view(), name='user_add'),
    url(r'^users/(?P<pk>\d+)/$', user.Detail.as_view(), name='user_detail'),
    url(r'^users/(?P<pk>\d+)/update/$', user.Update.as_view(), name='user_update'),
    url(r'^users/(?P<pk>\d+)/delete/$', user.Delete.as_view(), name='user_delete'),
    url(r'^users/(?P<pk>\d+)/lock/$', user.Lock.as_view(), name='user_lock'),
    url(r'^users/(?P<pk>\d+)/unlock/$', user.Unlock.as_view(), name='user_unlock'),
    url(r'^users/(?P<pk>\d+)/join_projects/$', user.JoinProjects.as_view(), name='user_join_projects'),
    url(r'^users/(?P<pk>\d+)/quit_project/(?P<id>\d+)$', user.QuitProject.as_view(), name='user_quit_project'),
    url(r'^users/(?P<pk>\d+)/join_groups/$', user.JoinGroups.as_view(), name='user_join_groups'),
    url(r'^users/(?P<pk>\d+)/quit_group/(?P<id>\d+)$', user.QuitGroup.as_view(), name='user_quit_group'),
    url(r'^users/(?P<pk>\d+)/projects/(?P<id>\d+)/roles$', user.Roles.as_view(), name='user_roles'),

    # group
    url(r'^groups/$', group.List.as_view(), name='group_list'),
    url(r'^groups/add/$', group.Create.as_view(), name='group_add'),
    url(r'^groups/(?P<pk>\d+)/update/$', group.Update.as_view(), name='group_update'),
    url(r'^groups/(?P<pk>\d+)/delete/$', group.Delete.as_view(), name='group_delete'),
    url(r'^groups/(?P<pk>\d+)/add_users/$', group.AddUsers.as_view(), name='group_add_users'),
    url(r'^groups/(?P<pk>\d+)/delete_user/(?P<id>\d+)$', group.DeleteUser.as_view(), name='group_delete_user'),
    url(r'^groups/(?P<pk>\d+)/join_projects/$', group.JoinProjects.as_view(), name='group_join_projects'),
    url(r'^groups/(?P<pk>\d+)/quit_project/(?P<id>\d+)$', group.QuitProject.as_view(), name='group_quit_project'),
    url(r'^groups/(?P<pk>\d+)/projects/(?P<id>\d+)/roles$', group.Roles.as_view(), name='group_roles'),

    # role
    url(r'^roles/$', role.List.as_view(), name='role_list'),
    url(r'^roles/add/$', role.Create.as_view(), name='role_add'),
    url(r'^roles/(?P<pk>\d+)/update/$', role.Update.as_view(), name='role_update'),
    url(r'^roles/(?P<pk>\d+)/delete/$', role.Delete.as_view(), name='role_delete'),

    # settings
    url(r'^settings/$', settings.Update.as_view(), name='settings'),
    url(r'^admin/$', project.Admin.as_view(), name='admin'),
    url(r'^admin/projects/$', project.Admin.as_view(), name='admin_project'),

    # status page
    url(r'^403/$', TemplateView.as_view(template_name="status/403.html"), name='status_403'),

    url(r'^django-admin/', include(admin.site.urls)),
]

src/apps/project/models.py
# coding:utf-8
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User


@python_2_unicode_compatible
class Project(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    homepage = models.CharField(max_length=255, default='', blank=True)
    is_public = models.BooleanField(default=True)
    parent_id = models.ForeignKey('Project', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    identifier = models.CharField(max_length=255, null=True, blank=True, unique=True)
    status = models.IntegerField(default=1)     # built-in: open,closed
    inherit_members = models.BooleanField(default=False)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Issue(models.Model):
    issue_type = models.ForeignKey('IssueType')
    project_id = models.ForeignKey('Project')
    subject = models.CharField(max_length=255, default='')
    description = models.TextField(null=True, blank=True)
    start_date = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    status = models.ForeignKey('IssueStatus')
    assigned_to = models.ForeignKey(User, null=True, blank=True)
    priority = models.IntegerField(default=1)       # built-in (low,normal,high,emergency,immediately)
    version = models.ForeignKey('Version', null=True, blank=True)
    author =  models.ForeignKey(User, related_name='created_by')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    done_ratio = models.IntegerField(default=0)
    parent_id = models.ForeignKey('Issue', null=True, blank=True)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.subject


@python_2_unicode_compatible
class IssueType(models.Model):
    name = models.CharField(max_length=30, default='', unique=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class IssueStatus(models.Model):
    name = models.CharField(max_length=30, default='', unique=True)
    default_done_ratio = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Version(models.Model):
    project = models.ForeignKey('Project')
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    wiki_page = models.CharField(max_length=255, null=True, blank=True)
    status = models.IntegerField(default=1)     # built-in (open,locked,closed)
    effective_date = models.DateTimeField()

    class Meta:
        unique_together = ("project", "name")

    def __str__(self):
        return self.name

src/pm/views/base.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib import messages

create_success_message = '%s was created successfully.'
update_success_message = '%s was updated successfully.'
delete_success_message = '%s was deleted successfully.'


class homepage(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')


def decorate_object(obj):
    return '\"%s\"' % obj


class SuccessMessageMixin(object):
    success_message = ''

    def form_valid(self, form):
        response = super(SuccessMessageMixin, self).form_valid(form)
        success_message = self.get_success_message()
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self):
        return self.success_message


class CreateSuccessMessageMixin(SuccessMessageMixin):
    def get_success_message(self):
        return self.success_message or create_success_message % decorate_object(self.object)


class UpdateSuccessMessageMixin(SuccessMessageMixin):
    def get_success_message(self):
        return self.success_message or update_success_message % decorate_object(self.object)


class DeleteSuccessMessageMixin(object):
    def delete(self, request, *args, **kwargs):
        success_message = self.get_success_message()
        if success_message:
            messages.success(self.request, success_message)

        return super(DeleteSuccessMessageMixin, self).delete(request, *args, **kwargs)

    def get_success_message(self):
        return delete_success_message % decorate_object(self.get_object())

src/pm/views/setting.py
from django.views.generic import View
from django.shortcuts import render
from ..models import Setting as SettingModel
from .auth import SuperuserRequiredMixin

_settings = ['app_name',
             'welcome_text',
             'file_size_limit',
             'entries_per_page',
             'text_format',
             'file_display_size_limit']


class Setting(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = dict()
        context['data'] = { n.name: n.value for n in SettingModel.objects.all() }
        return render(request, '_admin/settings.html', context=context)

    def post(self, request, *args, **kwargs):

        if 0 == SettingModel.objects.all().count():
            SettingModel.objects.bulk_create([ SettingModel(name=n, value=request.POST.get(n, '')) for n in _settings ])
        else:
            for n in _settings:
                if n in request.POST:
                    SettingModel.objects.filter(name=n).update(value=request.POST[n])
        context = dict()
        context['data'] = { n.name: n.value for n in SettingModel.objects.all() }
        return render(request, '_admin/settings.html', context=context)


def anonymous_access():
    return False     # TODO: data from settings

src/pm/views/settings.py
from django.views.generic import UpdateView
from django.core.urlresolvers import reverse_lazy
from ..models import Settings
from ..forms import UpdateSettingsForm
from .auth import SuperuserRequiredMixin
from .base import UpdateSuccessMessageMixin

_model = Settings
_form = UpdateSettingsForm


class Update(SuperuserRequiredMixin, UpdateSuccessMessageMixin, UpdateView):
    model = _model
    form_class = _form
    template_name = '_admin/settings.html'

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=1)

    def get_success_url(self):
        return reverse_lazy('settings')


def context_processors(request):
    from ..models import Settings
    return {'settings': Settings}

src/templates/project/settings/base.html
{% extends "project/base.html" %}

{% load permission_tags %}

{% block tab_toggle %}tab_settings{% endblock %}

{% block tab_content %}
  <div class="tab-caption">配置</div>
  <div class="tabbable">
    <ul class="nav nav-tabs second">
      {% get_user_perm user project as permissions %}
      {% if perms.pm.change_project %}
        <li id="tab_info"><a href="{% url 'project_update' project.id %}"> 信息 </a></li>
      {% endif %}

      {% if 'pm.manage_member' in permissions %}
        <li id="tab_member"><a href="{% url 'member_list' project.id %}"> 成员 </a></li>
      {% endif %}

      {% if 'pm.manage_version' in permissions %}
        <li id="tab_version"><a href="{% url 'version_list' project.id %}"> 版本 </a></li>
      {% endif %}

      {% if 'pm.manage_issue_category' in permissions %}
        <li id="tab_issue_category"><a href="{% url 'issue_category_list' project.id %}"> 问题类别 </a></li>
      {% endif %}
    </ul>
    <div class="tab-content no-space">
      <div id="settings-tab-content" tab-toggle="{% block settings_tab_toggle %}{% endblock %}">
        {% block settings_tab_content %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

src/templates/project/settings/info.html
{% extends "project/settings/base.html" %}

{% load i18n %}
{% load widget_tweaks %}

{% block settings_tab_toggle %}tab_info{% endblock %}

{% block settings_tab_content %}
  {% include 'form_success.html' %}
  <div class="portlet light grey-cararra bordered">
    <div class="portlet-body form">
      {% include "project_form.html" %}
    </div>
  </div>
{% endblock %}

src/templates/project/settings/issue_categories.html
{% extends "project/settings/base.html" %}

{% block settings_tab_toggle %}tab_issue_category{% endblock %}

{% block settings_tab_content %}
  {% include 'form_success.html' %}
  <div class="actions btn-set small btn-table">
    <a href="{% url 'issue_category_add' project.id %}"><i class="fa fa-plus"></i>新建问题类别</a>
  </div>
  <div class="dataTables_wrapper">
    <div class="table-scrollable">
      <table class="table table-light table-advance table-hover table-condensed second">
        <thead>
        <tr>
          <th><a name="btn-order" orderby="name">问题类别</a></th>
          <th width="110px"></th>
        </tr>
        </thead>
        <tbody>
        {% if issue_categories %}
          {% for category in issue_categories %}
            <tr>
              <td>{{ category.name }}</td>
              <td>
                <div class="actions btn-set small">
                  <a href="{% url 'issue_category_update' category.id %}"><i class="fa fa-edit"></i></a>
                  <a data-href="{% url 'issue_category_delete' category.id %}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash-o"></i></a>
                </div>
              </td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="2">{% include 'no_data.html' %}</td>
          </tr>
        {% endif %}
        </tbody>
      </table>
    </div>
    {% include "table_paging.html" %}
  </div>

  {% include "confirm_delete.html" %}
{% endblock %}

{% block page-level-scripts %}
<script>
  var page_url = '{% url 'issue_category_list' project.id %}';
  init_table_orderby(page_url, null);
</script>
{% endblock %}

src/templates/project/settings/members.html
{% extends "project/settings/base.html" %}

{% block settings_tab_toggle %}tab_member{% endblock %}

{% block settings_tab_content %}
  {% include 'form_success.html' %}
  <div class="actions btn-set small btn-table">
    <a data-toggle="modal" href="#add_member"><i class="fa fa-plus"></i>新建成员</a>
  </div>
  <div class="dataTables_wrapper">
    <div class="table-scrollable">
      <table class="table table-light table-advance table-hover table-condensed second">
        <thead>
        <tr>
          <th>用户/组</th>
          <th>角色</th>
          <th width="110px"></th>
        </tr>
        </thead>
        <tbody>
        {% if user_roles_deletable or group_roles %}
          {% for item in user_roles_deletable %}
            <tr>
              <td><a href="{% url 'user_detail' item.0.id %}">{{ item.0 }}</a></td>
              <td data-toggle="checkboxlist_form">
                <span>{% for role in item.1 %}{{ role.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>
              </td>
              <td>
                <div class="actions btn-set small">
                  <a name="btn-show-checkboxlist" data-href="{% url 'member_roles' project.id %}?user_id={{ item.0.id }}"><i class="fa fa-edit"></i>编辑</a>
                  {% if item.2 == True %}
                    <a data-href="{% url 'member_delete' project.id %}?user_id={{ item.0.id }}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash-o"></i>删除</a>
                  {% endif %}
                </div>
              </td>
            </tr>
          {% endfor %}
          {% for item in group_roles %}
            <tr>
              <td><i class="fa fa-group"></i> {{ item.0.name }}</td>
              <td data-toggle="checkboxlist_form">
                <span>{% for role in item.1 %}{{ role.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>
              </td>
              <td>
                <div class="actions btn-set small">
                  <a name="btn-show-checkboxlist" data-href="{% url 'member_roles' project.id %}?group_id={{ item.0.id }}"><i class="fa fa-edit"></i>编辑</a>
                  <a data-href="{% url 'member_delete' project.id %}?group_id={{ item.0.id }}" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash-o"></i>删除</a>
                </div>
              </td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="3">{% include 'no_data.html' %}</td>
          </tr>
        {% endif %}
        </tbody>
      </table>
    </div>
    {% include "table_paging.html" %}
  </div>

  <div class="modal fade bs-modal-lg" id="add_member" tabindex="-1">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">新建成员</h4>
        </div>
        <div class="modal-body">
          <form name="add_member_form" action="{% url 'member_add' project.id %}" method="post">
            {% csrf_token %}
            <div class="form-body">
              <div class="form-group">
                <div class="input-group">
                  <label>用户/组：</label>
                  {% if not_joined_users or not_joined_groups %}
                    <div class="icheck-inline">
                      {% for user in not_joined_users %}
                        <label><input type="checkbox" name="user" value="{{ user.id }}">{{ user }}</label>
                      {% endfor %}
                      {% for group in not_joined_groups %}
                        <label><input type="checkbox" name="group" value="{{ group.id }}">{{ group.name }}</label>
                      {% endfor %}
                    </div>
                  {% else %}
                    {% include "no_data.html" %}
                  {% endif %}
                </div>
              </div>
              <hr>
              <div class="form-group">
                <div class="input-group">
                  <label>角色：</label>
                  {% if roles %}
                    <div class="icheck-inline">
                      {% for role in roles %}
                        <label><input type="checkbox" name="role" value="{{ role.id }}">{{ role.name }}</label>
                      {% endfor %}
                    </div>
                  {% else %}
                    {% include 'no_data.html' %}
                  {% endif %}
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn default" data-dismiss="modal">关闭</button>
          <button type="button" class="btn green" onclick="document.add_member_form.submit()" disabled id="btn_add_member">保存</button>
        </div>
      </div>
    </div>
  </div>
  {% include "confirm_delete.html" %}
  {% include "_admin/checkboxlist_form.html" %}
{% endblock %}

{% block page-level-scripts %}
<script>
  $("input:checkbox[name='user'], input:checkbox[name='group'], input:checkbox[name='role']").change(function(){
    var member_len = $("input:checkbox:checked[name='user'], input:checkbox:checked[name='group']").length;
    var role_len = $("input:checkbox:checked[name='role']").length;
    var btn = $("#btn_add_member");
    (member_len == 0 || role_len == 0) ? btn.prop('disabled', true) : btn.prop('disabled', false);
  });
</script>
{% endblock %}

src/templates/project/settings/versions.html
{% extends "project/settings/base.html" %}

{% block settings_tab_toggle %}tab_version{% endblock %}

{% block settings_tab_content %}
  {% include 'form_success.html' %}
  <div class="actions btn-set small btn-table">
    <a href="{% url 'version_add' project.id %}?backurl="><i class="fa fa-plus"></i>新建版本</a>
  </div>
  <div class="dataTables_wrapper">
    <div class="table-scrollable">
      <table class="table table-light table-advance table-hover table-condensed second">
        <thead>
        <tr>
          <th><a name="btn-order" orderby="name">版本</a></th>
          <th>描述</th>
          <th><a name="btn-order" orderby="status">状态</a></th>
          <th><a name="btn-order" orderby="effective_date">有效日期</a></th>
          <th width="110px"></th>
        </tr>
        </thead>
        <tbody>
        {% if versions %}
          {% for version in versions %}
            <tr>
              <td>{{ version.name }}</td>
              <td>{{ version.description }}</td>
              <td>{{ version.get_status_display }}</td>
              <td>{{ version.effective_date|date:'Y-m-d'|default:"-" }}</td>
              <td>
                <div class="actions btn-set small">
                  <a href="{% url 'version_update' version.id %}?backurl="><i class="fa fa-edit"></i></a>
                  <a data-href="{% url 'version_delete' version.id %}?backurl=" data-toggle="modal" data-target="#confirm-delete"><i class="fa fa-trash-o"></i></a>
                </div>
              </td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="5">{% include 'no_data.html' %}</td>
          </tr>
        {% endif %}
        </tbody>
      </table>
    </div>
    {% include "table_paging.html" %}
  </div>
  {% include 'confirm_delete.html' %}
{% endblock %}

{% block page-level-scripts %}
<script>
  var page_url = '{% url 'version_list' project.id %}';
  init_table_orderby(page_url, null);
</script>
{% endblock %}